
version: "3.9"

services:
  client:
    build:
      context: ./front-end
      args:
        VITE_API_URL: https://group1.sustainability.it.ntnu.no
    ports:
      - "8181:8181"
    volumes:
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://server:8201
    depends_on:
      - server
    networks:
      - default

  server:
    build: ./back-end
    ports:
      - "8201:8201"
    volumes:
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
      - SECRET_KEY=hamburgerdressing
      - PORT=8201
    depends_on:
      - mongo
    networks:
      - default

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
    name: study-app-network
