

services:
  client:
    build:
      context: ./front-end
      args:
        VITE_API_URL: http://localhost:4202
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:4202
    depends_on:
      - server

  server:
    build: ./back-end
    ports:
      - "4202:4202"
    volumes:
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
      - SECRET_KEY=hamburgerdressing
      - PORT=4202

    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
